In [27]:
from matminer.datasets import load_dataset
import pandas as pd

# 下載 steel_strength 資料集
df = load_dataset('steel_strength')

# 顯示前幾行數據
print(df.head())

# 如果你想要將其保存到一個 CSV 文件中，可以使用以下命令
df.to_csv('./steel_strength.csv', index=False)

# 顯示資料集信息
print(df.info())

                                             formula     c    mn    si     cr  \
0  Fe0.620C0.000953Mn0.000521Si0.00102Cr0.000110N...  0.02  0.05  0.05   0.01
1  Fe0.623C0.00854Mn0.000104Si0.000203Cr0.147Ni0....  0.18  0.01  0.01  13.44
2  Fe0.625Mn0.000102Si0.000200Cr0.0936Ni0.129Mo0....  0.00  0.01  0.01   8.67
3  Fe0.634C0.000478Mn0.000523Si0.00102Cr0.000111N...  0.01  0.05  0.05   0.01
4  Fe0.636C0.000474Mn0.000518Si0.00101Cr0.000109N...  0.01  0.05  0.05   0.01

      ni    mo     v     n    nb     co     w    al    ti  yield strength  \
0  19.70  2.95  0.01  0.00  0.01  15.00  0.00  0.15  1.55          2411.5
1   0.01  3.01  0.46  0.04  0.01  19.46  2.35  0.04  0.00          1123.1
2  13.45  0.82  0.01  0.00  0.01  13.90  0.00  0.39  0.57          1736.3
3  17.70  3.95  0.01  0.00  0.01  15.00  0.00  0.13  1.47          2487.3
4  19.40  1.45  0.01  0.00  0.01  14.90  0.00  0.13  1.55          2249.6

   tensile strength  elongation
0            2473.5         7.0
1            1929.2         8.0
2            1871.8         NaN
3            2514.9         9.0
4            2315.0         8.5
<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 0 to 311
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   formula           312 non-null    object
 1   c                 312 non-null    float64
 2   mn                312 non-null    float64
 3   si                312 non-null    float64
 4   cr                312 non-null    float64
 5   ni                312 non-null    float64
 6   mo                312 non-null    float64
 7   v                 312 non-null    float64
 8   n                 312 non-null    float64
 9   nb                312 non-null    float64
 10  co                312 non-null    float64
 11  w                 312 non-null    float64
 12  al                312 non-null    float64
 13  ti                312 non-null    float64
 14  yield strength    312 non-null    float64
 15  tensile strength  312 non-null    float64
 16  elongation        303 non-null    float64
dtypes: float64(16), object(1)
memory usage: 43.9+ KB
None

In [28]:
display(df.head())

,formula,c,mn,si,cr,ni,mo,v,n,nb,co,w,al,ti,yield strength,tensile strength,elongation
0,Fe0.620C0.000953Mn0.000521Si0.00102Cr0.000110N...,0.02,0.05,0.05,0.01,19.70,2.95,0.01,0.00,0.01,15.00,0.00,0.15,1.55,2411.5,2473.5,7.0
1,Fe0.623C0.00854Mn0.000104Si0.000203Cr0.147Ni0....,0.18,0.01,0.01,13.44,0.01,3.01,0.46,0.04,0.01,19.46,2.35,0.04,0.00,1123.1,1929.2,8.0
2,Fe0.625Mn0.000102Si0.000200Cr0.0936Ni0.129Mo0....,0.00,0.01,0.01,8.67,13.45,0.82,0.01,0.00,0.01,13.90,0.00,0.39,0.57,1736.3,1871.8,NaN
3,Fe0.634C0.000478Mn0.000523Si0.00102Cr0.000111N...,0.01,0.05,0.05,0.01,17.70,3.95,0.01,0.00,0.01,15.00,0.00,0.13,1.47,2487.3,2514.9,9.0
4,Fe0.636C0.000474Mn0.000518Si0.00101Cr0.000109N...,0.01,0.05,0.05,0.01,19.40,1.45,0.01,0.00,0.01,14.90,0.00,0.13,1.55,2249.6,2315.0,8.5

In [44]:
from matminer.datasets import load_dataset
from matminer.featurizers.conversions import StrToComposition
from matminer.featurizers.composition import ElementProperty
from matminer.featurizers.composition import ElementFraction
import pandas as pd

# 下載 steel_strength 資料集
df = load_dataset('steel_strength')

# 將 formula 轉換為 Composition 對象
df = StrToComposition().featurize_dataframe(df, 'formula')

# 使用 ElementProperty 來提取元素屬性特徵
element_properties = ['Number', 'MendeleevNumber', 'AtomicWeight', 'MeltingT', 'Column', 'Row', 'CovalentRadius', 'Electronegativity']
stats = ['mean']
# stats = ['mean', 'std_dev', 'minimum', 'maximum', 'range']
ep_featurizer = ElementProperty(data_source='magpie', features=element_properties, stats=stats)
df = ep_featurizer.featurize_dataframe(df, 'composition', ignore_errors=True)
ef_featurizer = ElementFraction()
df = ef_featurizer.featurize_dataframe(df, 'composition', ignore_errors=True)

# 刪除原始的 formula 和 composition 列
df = df.drop(columns=['formula', 'composition'])

# 保存處理後的資料集到 CSV 文件
df.to_csv('steel_strength_features.csv', index=False)

# 顯示處理後的資料集的前幾行
display(df.head())
print(set(df))

StrToComposition:   0%|          | 0/312 [00:00<?, ?it/s]

ElementProperty:   0%|          | 0/312 [00:00<?, ?it/s]

ElementFraction:   0%|          | 0/312 [00:00<?, ?it/s]

,c,mn,si,cr,ni,mo,v,n,nb,co,...,Pu,Am,Cm,Bk,Cf,Es,Fm,Md,No,Lr
0,0.02,0.05,0.05,0.01,19.70,2.95,0.01,0.00,0.01,15.00,...,0,0,0,0,0,0,0,0,0,0
1,0.18,0.01,0.01,13.44,0.01,3.01,0.46,0.04,0.01,19.46,...,0,0,0,0,0,0,0,0,0,0
2,0.00,0.01,0.01,8.67,13.45,0.82,0.01,0.00,0.01,13.90,...,0,0,0,0,0,0,0,0,0,0
3,0.01,0.05,0.05,0.01,17.70,3.95,0.01,0.00,0.01,15.00,...,0,0,0,0,0,0,0,0,0,0
4,0.01,0.05,0.05,0.01,19.40,1.45,0.01,0.00,0.01,14.90,...,0,0,0,0,0,0,0,0,0,0

{'Pu', 'Zn', 'MagpieData mean CovalentRadius', 'Pd', 'Tc', 'Ho', 'si', 'Mo', 'Mn', 'Be', 'Ru', 'Gd', 'Rn', 'I', 'co', 'elongation', 'Au', 'Bi', 'w', 'Kr', 'ni', 'Zr', 'Ir', 'yield strength', 'He', 'Sm', 'v', 'Os', 'Es', 'As', 'MagpieData mean MeltingT', 'B', 'Cd', 'nb', 'Cr', 'Ni', 'Tl', 'Li', 'Pt', 'Rh', 'Ne', 'Mg', 'Fr', 'Lu', 'Co', 'Ag', 'Te', 'La', 'Cu', 'Lr', 'mn', 'Fe', 'H', 'Re', 'F', 'Hg', 'Sb', 'Nd', 'MagpieData mean Electronegativity', 'Tb', 'Bk', 'Fm', 'MagpieData mean MendeleevNumber', 'At', 'No', 'Ba', 'Ce', 'Sc', 'Ge', 'MagpieData mean AtomicWeight', 'Pr', 'Br', 'W', 'Ar', 'c', 'Th', 'tensile strength', 'Nb', 'Np', 'Sr', 'Po', 'Ac', 'Eu', 'Tm', 'Ta', 'Al', 'Er', 'Cm', 'K', 'S', 'Am', 'C', 'Cl', 'Ga', 'P', 'In', 'Cf', 'Md', 'Y', 'U', 'Hf', 'ti', 'al', 'mo', 'Yb', 'O', 'N', 'Se', 'Pb', 'Cs', 'Pa', 'Ti', 'V', 'Si', 'Ca', 'Ra', 'Pm', 'Dy', 'MagpieData mean Column', 'MagpieData mean Row', 'Sn', 'Xe', 'cr', 'MagpieData mean Number', 'Rb', 'Na', 'n'}

In [ ]:
# element_properties = [
    # 'Number', 'MendeleevNumber', 'AtomicWeight', 'MeltingT', 'Column', 'Row', 
    # 'CovalentRadius', 'Electronegativity', 'BoilingT', 'Density', 
    # 'HeatCapacityMass', 'ThermalConductivity', 'BulkModulus', 'ShearModulus',
    # # 'VickersHardness', 'AtomicVolume', 'BandGap', 'WorkFunction', 'ElectronAffinity'
    # 'AtomicVolume', 'BandGap', 'WorkFunction', 'ElectronAffinity'
# ]

In [50]:
df_cleaned = df.loc[:, (df != 0).any(axis=0)]
display(df_cleaned.head())
print(set(df_cleaned))

,c,mn,si,cr,ni,mo,v,n,nb,co,...,Ti,V,Cr,Mn,Fe,Co,Ni,Nb,Mo,W
0,0.02,0.05,0.05,0.01,19.70,2.95,0.01,0.00,0.01,15.00,...,0.018499,0.000112,0.000110,0.000521,0.619964,0.145992,0.191989,0.000062,0.017599,0.000000
1,0.18,0.01,0.01,13.44,0.01,3.01,0.46,0.04,0.01,19.46,...,0.000000,0.005151,0.147026,0.000104,0.623112,0.188034,0.000097,0.000061,0.017903,0.007291
2,0.00,0.01,0.01,8.67,13.45,0.82,0.01,0.00,0.01,13.90,...,0.006692,0.000110,0.093630,0.000102,0.625199,0.132042,0.129041,0.000060,0.004802,0.000000
3,0.01,0.05,0.05,0.01,17.70,3.95,0.01,0.00,0.01,15.00,...,0.017611,0.000113,0.000111,0.000523,0.634395,0.146091,0.173108,0.000062,0.023715,0.000000
4,0.01,0.05,0.05,0.01,19.40,1.45,0.01,0.00,0.01,14.90,...,0.018400,0.000112,0.000109,0.000518,0.635985,0.143997,0.187995,0.000061,0.008600,0.000000

{'MagpieData mean MeltingT', 'nb', 'C', 'Cr', 'MagpieData mean AtomicWeight', 'Ni', 'MagpieData mean CovalentRadius', 'W', 'si', 'ti', 'al', 'Mo', 'mo', 'c', 'Mn', 'Co', 'tensile strength', 'N', 'Nb', 'co', 'elongation', 'mn', 'Fe', 'Ti', 'V', 'w', 'Si', 'ni', 'MagpieData mean Column', 'MagpieData mean Row', 'yield strength', 'v', 'cr', 'MagpieData mean Number', 'Al', 'MagpieData mean Electronegativity', 'MagpieData mean MendeleevNumber', 'n'}